name: build

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.34.1"
      - run: mkdir dist
      - run: |
          deno compile --target x86_64-pc-windows-msvc --allow-read src/main.ts --output dist/windows.exe
          cd dist && zip windows.zip windows.exe
      - run: |
          deno compile --target aarch64-apple-darwin --allow-read src/main.ts --output dist/darwin
          cd dist && zip darwin.zip darwin
      - run: |
          deno compile --target x86_64-unknown-linux-gnu --allow-read src/main.ts --output dist/linux
          cd dist && zip linux.zip linux
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/windows.zip
            dist/darwin.zip
            dist/linux.zip